# Generated by Django 2.1.4 on 2018-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_token")]

    operations = [
        migrations.AddField(
            model_name="token",
            name="email",
            field=models.EmailField(default="", max_length=254),
        )
    ]
