# Generated by Django 2.1.4 on 2018-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_token_email")]

    operations = [
        migrations.AddField(
            model_name="token",
            name="uid",
            field=models.CharField(default="", max_length=40),
        )
    ]
