# Generated by Django 2.1.4 on 2018-12-21 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_token_uid")]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        )
    ]
