# Generated by Django 2.1rc1 on 2018-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lists", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="item", name="text", field=models.TextField(default="")
        )
    ]
